---
- name: Create /etc/containerd directory if it doesn't exist already.
  ansible.builtin.file:
    path: /etc/containerd/
    state: directory
    mode: "0644"
  become: true

- name: Copy pre-configured containerd config.toml
  ansible.builtin.copy:
    src: ../defaults/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Restart containerd service to apply configuration changes.
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true

