---
- name: Install containerd
  become: true
  block:

    - name: Download containerd
      ansible.builtin.get_url:
        url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/containerd-{{ containerd_version }}.tar.gz"
        mode: "0644"

    - name: Extract containerd binaries
      ansible.builtin.unarchive:
        src: "/tmp/containerd-{{ containerd_version }}.tar.gz"
        dest: /usr/local
        remote_src: true

    - name: Download systemd service file for containerd
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
        dest: /etc/systemd/system/containerd.service
        mode: "0644"

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: containerd
