---
- name: Check if Cilium CLI is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/cilium
  register: cilium_cli_installed

- name: Fail if Cilium CLI is not installed
  ansible.builtin.fail:
    msg: "Cilium CLI is not installed at /usr/local/bin/cilium"
  when: not cilium_cli_installed.stat.exists

- name: Check if Cilium is already on the cluster
  ansible.builtin.command: kubectl get deployment cilium-operator -n kube-system
  register: cilium_status
  ignore_errors: true
  changed_when: cilium_status.rc != 0
  
- name: Install Cilium on the cluster
  when: cilium_status.rc != 0
  block:
    - name: Install Cilium using Cilium CLI
      ansible.builtin.command: cilium install --version {{ cilium_version }} --set ipam.operator.clusterPoolIPv4PodCIDRList={{ lookup('env', 'pod_subnet') | default('10.32.0.0/16', true) }}
      register: cilium_install
      changed_when: cilium_install.rc != 0

    - name: Wait for Cilium to be fully ready
      ansible.builtin.command: cilium status --wait
      register: cilium_status_check
      changed_when: cilium_status_check.rc != 0