---
- name: Bootstrap Ansible environment from Terraform outputs
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Add Terraform-generated hosts to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: "{{ lookup('file', '../terraform/hosts.generated') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Terraform Hosts"

    - name: Bring hosts into Ansible directory
      copy:
        src: ../terraform/hosts.generated
        dest: ./hosts
        mode: '0644'

    - name: Copy Terraform-generated inventory to ansible directory
      copy:
        src: ../terraform/inventory.generated
        dest: ./inventory.ini
        mode: '0644'

    - name: Install Kubectl if not present
      include_role:
        name: install-kubectl
